import './globals.css';
import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import { Header } from '@/components/layout/Header';

const font = Quicksand({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
